version: "3.8"

x-common-variables: &common-variables
  NODE_ENV: ${NODE_ENV:?}
  ENCRYPTION_KEYS: ${ENCRYPTION_KEYS:?}
  AC_LOCAL_BASE_URL: ${AC_LOCAL_BASE_URL}
  WZ_USE_LOCAL_STORE: ${WZ_USE_LOCAL_STORE}

services:
  server:
    image: node:16-alpine
    # TODO run node as non-root
    command: ["node", "-r", "./server/src/preload.js", "server/src/main.js"]
    working_dir: /var/workzone-server/
    volumes:
      - ./server/app:/var/workzone-server/
      - workzone-socket:/var/run/workzone/
    environment:
      <<: *common-variables

  client:
    image: nginx:mainline
    volumes:
      - ./client/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./client/static:/workzone-client
      - /var/log/nginx/healthd/:/var/log/healthd-nginx/
      - "${EB_LOG_BASE_DIR:-..}/client:/var/log/nginx"
      - workzone-socket:/var/run/workzone/
    ports:
      - "${PROXY_PORT:-80}:5000"
    depends_on:
      - server

volumes:
  workzone-socket:
    external: false
